app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask, name='ask'),
    path('question/<int:question_id>', views.question, name='question'),
    path('tag/<str:id_tag>', views.tag, name='tag'),
    path('hot/', views.hot, name='hot'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('settings/', views.settings, name='settings'),
    path('like/', views.like, name='like'),
    path('correct/', views.is_correct, name='correct'),
    path('search/', views.search, name="search"),
]

askme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

templates/ask.html
{% extends "./base/base.html" %}

{% block title %}
Ask
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>New Question</h1>
</div>

<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="row mb-3">
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-8">
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% if field.errors %}
                    <div class="invalid-feedback d-block">
                        {{ field.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <div class="row mt-3">
        <div class="col-2"></div>
        <div class="col-10">
            <button type="submit" class="btn btn-primary">Ask</button>
        </div>
    </div>
</form>
{% endblock content %}

templates/hot.html
{% extends "./base/base.html" %}
{% load static %}

{% block title %}
hot
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>Hot questions</h1>
</div>
<div class="d-flex flex-column gap-3">
    {% for question in content.page_items.object_list %}
        {% include "components/questioncard.html" %}
    {% endfor %}
</div>
{% include "components/pagination.html" %}
{% endblock content %}

{% block jscode %}
    <script src="{% static './js/like.js' %}"></script>
{% endblock jscode %}

templates/index.html
{% extends "./base/base.html" %}
{% load static %}

{% block title %}
main page
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>New Questions</h1>
    <a href="{% url 'app:hot' %}">Hot Questions</a>
</div>
<div class="d-flex flex-column gap-3">
    {% for question in content.page_items.object_list %}
        {% include "components/questioncard.html" %}
    {% endfor %}
</div>
{% include "components/pagination.html" %}
{% endblock content %}

{% block jscode %}
    <script src="{% static './js/like.js' %}"></script>
{% endblock jscode %}

templates/login.html
{% extends "./base/base.html" %}

{% block title %}
login
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>Log In</h1>
</div>

{% if form.non_field_errors %}
    <div class="mb-3 text-danger">
        {{ form.non_field_errors }}
    </div>
{% endif %}

<form method="post">
    {% csrf_token %}
    {% for form_field in form %}
        <div class="row mb-3">
            <label for="{{ form_field.id_for_label }}" class="col-sm-2 col-form-label">{{ form_field.label }}</label>
            <div class="col-sm-4">
                {{ form_field }}
                <div class="invalid-feedback d-block">
                    {{ form_field.errors }}
                </div>
            </div>
        </div>
    {% endfor %}
    
    {% if request.GET.continue %}
        <input type="hidden" name="continue" value="{{ request.GET.continue }}">
    {% endif %}

    <div class="row mt-3">
        <div class="col-2">
        </div>
        <div class="col-10">
            <button type="submit" class="btn btn-primary">Log in</button>
        </div>
    </div>

    <div>
        <a href="{% url 'app:signup' %}">Create new account</a>
    </div>
</form>
{% endblock content %}

templates/profile-settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <a class="navbar-brand" href="">AskPupkin</a>

                <form class="d-flex flex-grow-1" role="search">
                    <div class="">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                    </div>
                </form>

                <button class="btn btn-success m-2" type="submit">Ask</button>

                <div class="d-flex gap-1">
                    <img src="jpg.jpg" alt="Avatar" class="img-thumbnail">
                    <div>
                        <div>
                            FoxiesSanya
                        </div>
                        <a href="#">settings</a>
                        <a href="#">log out</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <main class="container mt-3">
        <div class="d-flex gap-3 align-items-center">
            <h1>Settings: FoxiesSanya</h1>
        </div>
        <div class="row">
            <div class="col-9">
                <form action="" role="question">
                    <div class="row mb-3">
                        <label for="form-elem-1" class="col-sm-2 col-form-label">Login</label>
                        <div class="col-sm-4">
                            <input type="login" id="form-elem-1" class="form-control" placeholder="Enter your login here" />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="form-elem-1" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-4">
                            <input type="login" id="form-elem-1" class="form-control" placeholder="Enter your email here" />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="form-elem-1" class="col-sm-2 col-form-label">Nickname</label>
                        <div class="col-sm-4">
                            <input type="login" id="form-elem-1" class="form-control" placeholder="Enter your nickname here" />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="formFile" class="col-sm-2 form-label">Upload avatar</label>
                        <div class="col-sm-4">
                            <img src="jpg.jpg" alt="Avatar" class="img-thumbnail" style="width: 150px; height: 150px;">
                            <input class="form-control" type="file" id="formFile">
                        </div>
                      </div>
                </form>
                <button type="save" class="btn btn-secondary">Save</button>
            </div>
            <div class="col">
                <section class="mb-3">
                    <h2>Popular Tags</h2>
                    <div>
                        <span class="badge text-bg-primary">Primary</span>
                        <span class="badge text-bg-secondary">Secondary</span>
                        <span class="badge text-bg-success">Success</span>
                        <span class="badge text-bg-danger">Danger</span>
                        <span class="badge text-bg-warning">Warning</span>
                        <span class="badge text-bg-info">Info</span>
                        <span class="badge text-bg-light">Light</span>
                        <span class="badge text-bg-dark">Dark</span>
                    </div>
                </section>

                <section>
                    <h2>Best members</h2>
                    <div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><a href="#">Member</a></li>
                            <li class="list-group-item"><a href="#">Member</a></li>
                            <li class="list-group-item"><a href="#">Member</a></li>
                            <li class="list-group-item"><a href="#">Member</a></li>
                            <li class="list-group-item"><a href="#">Member</a></li>
                        </ul>
                    </div>
                </section>

            </div>

        </div>


    </main>
    <script src="../static/js/bootstrap.min.js"></script>
</body>
</html>

templates/question.html
{% extends "./base/base.html" %}
{% load static %}

{% block title %}
question
{% endblock title %}

{% block content %}
{% include "components/questioninfo.html" %}

<hr>
<div id="answers-container" class="d-flex flex-column gap-3">
    {% if content.page_items.object_list %}
        {% for answer in content.page_items.object_list %}
            <div id="answer-{{ answer.id }}">
                {% include "components/answer.html" %}
            </div>
        {% endfor %}
    {% else %}
        <div class="d-flex justify-content-center align-items-center text-center">
            <h3 class="text-muted">No answers</h3>
        </div>
    {% endif %}
</div>

{% include "components/pagination.html" %}
<hr id="end">

{% if request.user.is_authenticated %}
    <form method="post" id="answer-form">
        {% csrf_token %}
        {% for form_field in form %}
            <div class="form-group mb-3">
                {{ form.content }}
            </div>
        {% endfor %}
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Answer</button>
        </div>
    </form>
{% endif %}

{% endblock content %}

{% block jscode %}
    <script src="{% static './js/like.js' %}"></script>
    <script src="{% static './js/is_correct.js' %}"></script>
    <script src="https://unpkg.com/centrifuge@5.0.1/dist/centrifuge.js"></script>
    <script>
        const centrifuge = new Centrifuge("{{ ws_url }}", {
            token: "{{ token }}"
        });
        const sub = centrifuge.newSubscription('room:{{ question.id }}');
        sub.on('publication', function(ctx) {
            console.log(ctx.data);
        })
        sub.subscribe();
        centrifuge.connect();
    </script>
{% endblock jscode %}

templates/settings.html
{% extends "./base/base.html" %}

{% block title %}
settings
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>Settings: {{ user.username }}</h1>
</div>

{% if form_updated %}
<div class="alert alert-success" role="alert">
  Changes saved successfully!
</div>
{% endif %}

{% if form.non_field_errors %}
    <div class="mb-3 text-danger">
        {{ form.non_field_errors }}
    </div>
{% endif %}

<form method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {% for form_field in form %}
        <div class="row mb-3">
            <label for="{{ form_field.id_for_label }}" class="col-sm-2 col-form-label">{{ form_field.label }}</label>
            <div class="col-sm-4">
                {{ form_field }}
                <div class="invalid-feedback d-block">
                    {{ form_field.errors }}
                </div>
            </div>
        </div>
    {% endfor %}

    {% for form_field in avatar %}
    <div class="row mb-3">
        <div class="col-2">
        </div>
        <div class="col-sm-4">
            <div class="mb-2">
                <img src="{{ request.user.profile.avatar.url }}" alt="Avatar" class="img-thumbnail profilePictureSettings">
            </div>
            {{ avatar }}
            <div class="invalid-feedback d-block">
                {{ avatar.errors }}
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="row mt-3">
        <div class="col-2">
        </div>
        <div class="col-10">
            <button type="submit" class="btn btn-primary">Update profile</button>
        </div>
    </div>
</form>
{% endblock content %}

templates/signup.html
{% extends "./base/base.html" %}

{% block title %}
sign up
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>Registration</h1>
</div>

{% if form.non_field_errors %}
    <div class="mb-3 text-danger">
        {{ form.non_field_errors }}
    </div>
{% endif %}

<form method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {% for form_field in form %}
        <div class="row mb-3">
            <label for="{{ form_field.id_for_label }}" class="col-sm-2 col-form-label">{{ form_field.label }}</label>
            <div class="col-sm-4">
                {{ form_field }}
                <div class="invalid-feedback d-block">
                    {{ form_field.errors }}
                </div>
            </div>
        </div>
    {% endfor %}

    <div class="row mt-3">
        <div class="col-2">
        </div>
        <div class="col-10">
            <button type="submit" class="btn btn-primary">Sign up</button>
        </div>
    </div>
</form>
{% endblock content %}

templates/tag.html
{% extends "./base/base.html" %}
{% load static %}

{% block title %}
tag
{% endblock title %}

{% block content %}
<div class="d-flex gap-3 align-items-center">
    <h1>Tag: {{ tag.tag }}</h1>
</div>
<div class="d-flex flex-column gap-3">
    {% for question in content.page_items.object_list %}
        {% include "components/questioncard.html" %}
    {% endfor %}
</div>
{% include "components/pagination.html" %}
{% endblock content %}

{% block jscode %}
    <script src="{% static './js/like.js' %}"></script>
{% endblock jscode %}